Add spotless with ktlint
navikt/tpts-tiltakspenger-mottak pull request #11
Opened 2021-12-08 08:08 UTC by tu55eladd

2021-12-08 08:47 UTC, pjwalstrom commented
Ble vi virkelig enige om å bruke Spotless?

2021-12-08 08:50 UTC, pjwalstrom requested changes
Spotless er bare ett av flere alternativer. Vi har .editorconfig, SonarCloud, og Detekt kjører allerede på Github. Samma for meg hva vi bruker, men vi bør bare bruke én. Ulike regler gir bare krøll.

2021-12-08 10:06 UTC, pjwalstrom commented
Om vi får inn regelsettet til Spotless/Ktlint på en **enkel og automatisk** måte i IntelliJ, er jeg for :-)

2021-12-09 13:00 UTC, tu55eladd commented
Både SonarCloud og Detekt ser for meg ut til å være mye mer enn bare en linter slik ktlint er, disse gjør jo også statisk kode-analyse(?). Gjør de linting og evt formatting i tillegg?

2021-12-21 10:36 UTC, closed without merging