Tk2 hent metadata saf graphql
navikt/tpts-tiltakspenger-mottak pull request #21
Opened 2022-02-03 15:23 UTC by sneha-d-desai

### 💰 Hva forsøker du å løse i denne PR'en
Henter metadata (dokumentInfoId, dokumentTittel, JournalfortId) om strukturert dokument av søknaden 

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [ ] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [ ] Jeg har skrevet tester. 

### 🤷‍♀ ️Hvor er det lurt å starte?
SafClient.kt

Har gjort muntlig gjennomgang før

2022-02-04 12:01 UTC, pjwalstrom commented
@sneha-d-desai får du til å bygge lokalt og pusher fiks? Venter med gjennomganen til det bygger :-)

2022-02-04 12:32 UTC, tu55eladd commented on src/main/kotlin/no/nav/tpts/mottak/applications/ApplicationRoutes.kt
> +    route("/api/soknad/{journalPostId}") {
Vi har diskutert litt og blitt enige om at vi ikke trenger gjøre noen endringer i denne filen enda. Mulig den bør fjernes etterhvert

2022-02-04 14:55 UTC, sneha-d-desai commented
> @sneha-d-desai får du til å bygge lokalt og pusher fiks? Venter med gjennomganen til det bygger :-)



> @pjwalstrom Den ble bygget opp på nytt :)

2022-02-06 19:47 UTC, pjwalstrom requested changes

2022-02-06 19:47 UTC, pjwalstrom commented on src/main/kotlin/no/nav/tpts/mottak/applications/ApplicationRoutes.kt
> +                e.printStackTrace()
Ser at det er kommentert ut, da kan vi vel bare slette det?

Ellers bør vi nok bruke en logger istedenfor printStackTrace. Foreslår
```kotlin
val LOG = KotlinLogging.logger {}
```
og deretter 
```kotlin
LOG.error(e) { e.message }
```

2022-02-06 19:47 UTC, pjwalstrom commented on src/main/kotlin/no/nav/tpts/mottak/clients/HttpClient.kt
> +            level = LogLevel.BODY
lurer på om `LogLevel.BODY` er lurt. Ser det logger tokens. Men det kan vi diskutere

2022-02-06 19:47 UTC, pjwalstrom commented on src/main/kotlin/no/nav/tpts/mottak/clients/saf/SafClient.kt
> +const val SAF_URL = "https://saf.dev-fss-pub.nais.io"
kanskje flytte denne til `Configuration` og ha en for dev og en for prod?

2022-02-06 19:47 UTC, pjwalstrom commented on src/main/kotlin/no/nav/tpts/mottak/clients/saf/SafClient.kt
> +            header("Authorization", "(Bearer $token")
for header names (Authorization, Accept, Content-Type) og verdier (application/json) kan du gjerne bruke konstanter, f.eks. de som finnes i `HttpHeaderNames` eller annen egnet ktor-klasse

2022-02-06 19:47 UTC, pjwalstrom commented on src/main/kotlin/no/nav/tpts/mottak/clients/saf/SafClient.kt
> +        if (safResponse.errors?.get(0)?.message?.isNotEmpty() == true) {
`==true` er vel overflødig?

2022-02-06 19:47 UTC, pjwalstrom commented on src/main/kotlin/no/nav/tpts/mottak/graphql/Graphql.kt
> +data class GraphqlErrorLocation(
trenger vi denne?

2022-02-08 08:11 UTC, tu55eladd commented on src/main/kotlin/no/nav/tpts/mottak/clients/saf/SafClient.kt
> +        if (safResponse.errors?.get(0)?.message?.isNotEmpty() == true) {
Burde egentlig sjekke errors istedetfor meldingen på første error? `safResponse.errors.isNotEmpty()`

2022-02-10 09:26 UTC, merged